:source-highlighter: pygments

= Create a remote statebucket

The cloudspin example code is implemented in Terraform, which uses https://www.terraform.io/docs/state/[state files] to map the resources it manages to your project code.

There are various ways to manage Terraform state, in our case, we will store it in an S3 bucket. This preserves the state in the event that anything happens to your local files (e.g. accidentally deleting local statefiles). It also allows multiple people to work on the same infrastructure instances.


== State for your statebucket

Where does the statefile for the stack that manages your statefile bucket live? Once you've created your bucket, you'll migrate your state to it. So the terraform state for the stack that manages your bucket lives within the bucket itself.


== Planning and creating your statebucket

The folder `00-statebucket` has a cloudspin project that will create a statebucket for you. This uses the https://github.com/cloudspinners/spin-stack-s3bucket[s3bucket stack] definition. Here's how to do it.


=== (1) Create a local configuration file

Create a file `00-statebucket/stack-statebucket-local.yaml` (you can copy `00-statebucket/stack-statebucket-local-example.yaml` as a starter), and edit it:

[source,yaml]
----
instance:
  group: YOURNAME_sandbox

resources:
  aws_profile: YOUR_BOOTSTRAP_CREDENTIALS_PROFILE
----

_YOUR_BOOTSTRAP_CREDENTIALS_PROFILE_ will be the name of the profile in `~/.aws/credentials` with the bootstrap AWS API keys you created if you followed the steps in the link:00-starting/setup-aws.adoc[previous page].

The `group` setting doesn't matter too much. It's essentially an ID for your environment, which, in more complex setups, can be used to integrate different things together. It is also used in tags.


=== (2) Initialize the local project tooling

In your `00-statebucket` folder, run:

[source,console]
----
bundle install
----

This installs some Ruby gems that include the cloudspin tools we use in these examples. This is essentially a one-off, but when you want to update to newer versions of the tools, you'd run `bundle update`.


=== (3) Plan the bucket creation

Now you can see what changes Terraform will make:

[source,console]
----
rake plan
----

This downloads the https://github.com/cloudspinners/spin-stack-s3bucket[cloudspin s3 bucket stack definition] code, and then runs `terraform plan`.


=== (4) Create the bucket

[source,console]
----
rake up
----

Now you should have an S3 bucket that can be used for storing Terraform state. You'll need the name of the bucket to put into configuration for further examples. The name should be something like: `statebucket-cloudspin-examples-xxxxxxxxxxxx`, where the number at the end is your AWS account ID (which is needed to make sure the bucket name is globally unique).


=== (5) Migrate your state to the bucket

Now you need to migrate your terraform state, which is currently in a local folder (`./state/YOURNAME_sandbox`), to the S3 bucket. This will allow other people in your team to make changes to the statebucket stack.

The process to do this (and keep in mind, this cloudspin tooling is for proof of concept, so this is clunkier than we'd like) is to edit your local configuration, including setting a temporary option to make the migration happen:


[source,yaml]
----
instance:
  group: YOURNAME_sandbox

resources:
  aws_profile: YOUR_BOOTSTRAP_CREDENTIALS_PROFILE

terraform_backend:
  bucket: YOURNAME_sandbox-XXXXXXXXXXXX
  profile: YOUR_BOOTSTRAP_CREDENTIALS_PROFILE
  region: eu-west-1
  encrypt: true
  migrate: true
----

You can then run `rake dry` to see that there are no obvious errors. Unlike other actions, for migrating state from local to the remote bucket, the *plan* command _will make it happen!_ This is because the "plan" command uses the state, so it carries out changes to backend, although it still won't try to make changes to the infrastructure in the stack it actually manages.

When you do run:

[source,console]
----
rake plan
----

then you should expect to see the following in the output:

[source,console]
----
Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.
----

This shows that the bucket will be used for state. At the end, you should also see:

[source,console]
----
No changes. Infrastructure is up-to-date.
----

If instead you see that terraform will create all of the infrastructure elements, even though they already exist, then this usually means your state did not get migrated up to the s3 bucket.


=== (6) Change your configuration to use the bucket for state

This is the clunkiest part. You need to remove the `migrate` flag from your local configuration, so that cloudspin doesn't try to migrate old local state again.


[source,yaml]
----
terraform_backend:
  ...
  # migrate: true
----

Comment out (or delete) this line from the file. The re-run `rake plan`, and make sure it's all happy. I tend to also move the local state folder somewhere else, and re-run `rake plan`, `rake up`, etc. to make sure it's all good.


=== (7) After IAM stack, switch to using the IAM roles

The next step of this tutorial is to create IAM roles that are used to run terraform more securely. Once those have been created, you can switch this stack to use those roles by editing your `stack-instance-local.yaml` file for this statebucket stack:


[source,yaml]
----
resources:
  aws_profile: YOUR_UNPRIVEGED_CREDENTIALS_PROFILE
  assume_role_profile: YOUR_ASSUME_DELIVERY_ROLE_PROFILE
  assume_role_arn: arn:aws:iam::XXXXXXXXXXXX:role/spin_role-cloudspin_examples-delivery

terraform_backend:
  bucket: YOURNAME_sandbox-XXXXXXXXXXXX
  profile: YOUR_UNPRIVEGED_CREDENTIALS_PROFILE
  role_arn: arn:aws:iam::XXXXXXXXXXXX:role/spin_role-cloudspin_examples-manager
  region: eu-west-1
  encrypt: true
  # migrate: true (or delete this line)
----


=== Did you do all that?
[CAUTION]
====

If you've simply followed all of these instructions without having a close look at the code they apply to your cloud account, you have potentially put yourself at risk. This project code could easily have been created by someone unscrupulous. Even if you trust me and know this is my project, someone else could have compromised my project code, and inserted code to exploit your AWS account.

You should make it a habit to carefully vet code before you download and apply it.

In this case, the Ruby gems will have been downloaded into your local Ruby library folder, and the Terraform code will have been downloaded to `./00-statebucket/.cloudspin`. I'd encourage you to review this code and make sure you're comfortable with what it does before running it.
====


== What next?

Now you can proceed to link:00-starting/setup-iam-roles.adoc[setting up IAM roles] to use your AWS account a bit more securely.

