require 'rake/clean'
require 'cloudspin/stack/rake'

CLEAN.include('work')
CLOBBER.include('state')

include Cloudspin::Stack::Rake

stack = StackTask.new(id: 'test-network').instance
InspecTask.new(stack_instance: stack)

