:source-highlighter: pygments

# Reference: Cloudspin project structure

This defines a standard project structure for an infrastructure stack. The goals of having this standardized include:

- Make it easy for people who've worked with this structure before to understand and work with new infrastructure stack code.
- (Hopefully) make it easy for people who haven't worked with this structure to learn it.
- Avoid wasting time haggling with people on your team about how to structure your project. Just use ours. ;-)
- Write scripts, tools, etc. that can work across all your infrastructure projects
- Use scripts, tools, etc. that were written by other people using this same structure

## Top level stack project structure

Each stack definition can include the following top level folders and files, which should be checked into source control:

|===
| `./src` | Stack definition code, i.e. Terraform source code (*.tf files)
| `./test` | Code used to test stack definitions. Not run against production environments, as it may be destructive.
| `./roles` | Configuration for stack roles (tbc)
| `./instances` | Configuration for stack instances (tbc)
| `./pipeline` | Delivery pipeline definition code. Typically run to add pipeline stages to a CI or CD service.
| `./monitoring` | Code used to monitor stack instances. Typically run to add monitoring checks to a monitoring service. (tbc)
| `./smoke` | Code to run after provisioning or updating a stack instance, to validate it (tbc)
| `./stack-instance-defaults.yaml` | Default parameters for stack instances and roles
| `./Rakefile` | Optional rakefile for stack management and test tasks. See link:cloudspin-rake.adoc[Cloudspin Rake tasks] for more information.
| `./Gemfile` | Optional, needed if you're using rake to make sure the required gems are available
| `./Gemfile.lock` | Optional, useful if you're using rake to ensure consistent versions of gems are used
|===

Some of these are "(tbc)", meaning it's an aspirational thing that hasn't been worked on yet.

There is also at least one file that can be added to local instances of your project, but not added to source control:

|===
| `./stack-instance-local.yaml` | Override parameter values when you work with stack instances from your local machine. Often used for user-specific information such as AWS profiles to use. Avoid putting secrets in this file, in case it is accidentally committed to a public repository (easier than you think!)
|===

And, there are a few folders that may be created by cloudspin tools for various purposes, which should normally not be committed to version control:

|===
| Folder | What is it | When is it destroyed

| `./work` | Various files are copied or created under here as a part of stack instance management, and testing. This includes logfiles, temporary files, and a copy of the stack definition code. | This folder is deleted on nearly every run of the stack or rake commands. `rake clean` removes it.
| `./state` | Terraform local statefiles are stored in this folder. | Only destroyed when `rake clobber` is run. Losing these files while you have an instance running means you can't use cloudspin tools to destroy or change your instance - it becomes orphaned, and so must be deleted manually.
| `./dist` | Artefacts are built here, including a copy of the files to be packaged, and the artefact package itself.
|===


## Stack definition configuration file

As mentioned, the `./src` folder holds the stack definition, i.e. the terraform code. It also normally has a file `./src/stack-definition.yaml`, which includes some configuration information used by the cloudspin tools.

At the moment this is fairly minimal:

[source,yaml]
----
stack:
  name: basic-stack-01
  version: 0.0.1
----

These parameters are used by the link:cloudspin-artefacts.adoc[cloudspin artefacts] to name the artefact package for the stack definition.

In the future, things could be added to this file to define integration points and dependencies between stacks.


## Configuring stack instances

There are a number of configurations which may be customizable for each stack instance. For example, *parameters* are values that are passed to the infrastructure code (i.e. terraform variables) for the instance. *Resources* are configuration settings which are used to run terraform (and perhaps other tools), but not passed as variables to the terraform code. Examples of resources include AWS credential profiles and roles, and remote state configuration options.

These parameters can be provided in different ways, depending on which tooling is used to manage a stack instance.


### Stack instance configuration files

The *stack* command line tool, and the default rake tasks, will look for the following yaml configuration files and load configuration from them if found:

|===
| `./stack-instance-defaults.yaml`
| `./stack-instance-local.yaml`
|===

By convention, the -defaults file is committed to source control, and so has values that may be useful to any instance of the stack.

The -local file is not committed to source control, and so is used by developers to set values they want to use when managing stacks locally, typically while working on the stack definition code.

Any configuration values found in `./stack-instance-local.yaml` will override values defined in `./stack-instance-defaults.yaml`.

These yaml files (currently) have two top level options, `parameters` and `resources`. Here's an example:

[source,yaml]
----
parameters:
  region: "eu-west-1"
  availability_zones: "eu-west-1a,eu-west-1b,eu-west-1c"
resources:
  aws_profile: my-cloudspin-user
  assume_role_arn: arn:aws:iam::000000000000:role/my-cloudspin-iam-role
----

### Overriding the instance configuration file locations

Both the command line tool, and the rake task, can override the list of configuration files that will be loaded. See the respective references for them for more information on how to do this.

